### ISSUE TITLE
Share code > Embed iframe not working

### ISSUE THREAD

**Issue by fernandospr** [JetBrains/kotlin-playground#103]
Using the **Share > Embed** option from the [Kotlin Playground](https://play.kotlinlang.org/) will generate something similar to this code:
`<iframe src="https://pl.kotl.in/gIk0UQVi1"></iframe>`

However, embedding this into a web page won't always render the code. E.g. pasting it in [https://codepen.io/pen/](https://codepen.io/pen/).

The same happens if you try to open [https://pl.kotl.in/gIk0UQVi1](https://pl.kotl.in/gIk0UQVi1) in a browser, it won't render it until you perform a CMD + R.

**Comment by sureshg** [comment]
I am also facing the same issue. Is there any workaround for this? Console log shows `Empty state of playground. Key: xxxxxx`

**Comment by krzema12** [comment]
I just had the same with `<iframe src="https://pl.kotl.in/_Fk8K5YRA"></iframe>`. It didn't work for two page refreshes, then it worked once (I thought it was a matter of some eventual consistency happening), then it stopped working. I was hoping to embed some snippets into my reveal.js presentation (#27), but seems it's too risky :sweat_smile:

**Comment by fernandospr** [comment]
@krzema12 The workaround I'm currently using to embed code is to include the script `<script src="https://unpkg.com/kotlin-playground@1" data-selector="code"></script>` and then paste the code.

Example:
```html
<script src="https://unpkg.com/kotlin-playground@1" data-selector="code"></script>
<code>
fun main() {
   println("Hello world")
}
</code>
```
This is explained [here](https://jetbrains.github.io/kotlin-playground/).

**Comment by nikpachoo** [comment]
Finally fixed 🎉
