### ISSUE TITLE
Examples are partially broken

### ISSUE THREAD

**Issue by holgerbrandl** [JetBrains/kotlin-playground#105]
When opening the examples from the repo landing page,  two of them do not work and throw errors instead:

![image](https://user-images.githubusercontent.com/200952/99382081-428e6600-28cc-11eb-997f-01a3e90d526f.png)

**Comment by AlexanderPrendota** [comment]
Hey, thanks for the feedback. The first one is correct. Please write some code in TODO() section. @zoobestik Please have a look at the canvas example.

**Comment by holgerbrandl** [comment]
Imho, the first "failing" example lacks intuition: there is just a function declaration but no callsite, so why is the code throwing an error? I think if there would be a little plus sign (as for some of the other examples) that details out an execution context (main, test or similar) it would be easier to follow.

**Comment by zoobestik** [comment]
Canvas has little bit legacy for 1.4. Actual code in [this PR)(https://github.com/JetBrains/kotlin-playground/pull/106).

**Comment by zoobestik** [comment]
@holgerbrandl about first point,

it's example about **unfolded** code - `just set the attribute folded-button to false value.`
It's clear with full code.

If you don't like it, just will not use attribute or folding at all.

![Screenshot 2020-11-21 at 02 49 44](https://user-images.githubusercontent.com/242514/99860589-8622f180-2ba4-11eb-9d1a-3f674ff05758.png)

Or what is your real case?
