### ISSUE TITLE
Problem with `Ctrl + J` in Chrome + Linux

### ISSUE THREAD

**Issue by skuzmich** [JetBrains/kotlin-playground#124]
"Show generated JS code" action is bound to `Ctrl + J` on Linux which instead opens a Download tab in Chrome.

Could you, please, make it as an on-screen button or choose a key combination that would work on all systems?

**Comment by nikpachoo** [comment]
@skuzmich thanks for your feedback. We [take a look](https://youtrack.jetbrains.com/issue/KT-46745) at how we can improve that.

**Comment by nikpachoo** [comment]
Now "Show generated JS code" action is bound to Alt + J on Linux and Windows.
