### ISSUE TITLE
[Bug] Online playground is not working

### ISSUE THREAD

**Issue by rami3l** [JetBrains/kotlin-playground#137]
![pic](https://user-images.githubusercontent.com/33851577/141648788-8960dafa-046b-4b41-ac32-7f28b8c5d211.jpg)

I don't know if this is the right place to post, but I came across the Kotlin Playground today and encountered the following error:

```kt
Exception in thread "main" java.io.FileNotFoundException: /var/task/tmp/578c4a4c065841fea2fa62b22ca58b9e/executor.policy (No such file or directory)
 at java.io.FileOutputStream.open0 (FileOutputStream.java:-2) 
 at java.io.FileOutputStream.open (FileOutputStream.java:270) 
 at java.io.FileOutputStream.<init> (FileOutputStream.java:213) 
```

Steps to reproduce:

1. Go to https://play.kotlinlang.org/
2. Click `Run` when the default "Hello, World" program shows up

**Comment by nikpachoo** [comment]
@rami3l, thank you! We are working on fixing the problem.

**Comment by Harri1970** [comment]
I just started this Kotlin course and first hello world was not working, nice that I found this bug here. I will wait.

**Comment by Bediruna** [comment]
Yes, I am experiencing this as well. The android playground is not working as well. https://developer.android.com/training/kotlinplayground

**Comment by blackcrown01** [comment]
still after 4hours since the bug was reported the kotlin playground still to this moment out  ???

**Comment by Bediruna** [comment]
> still after 4hours since the bug was reported the kotlin playground still to this moment out  ??? 
> 

Well actually I started experiencing this yesterday. So it's been more than that.

**Comment by SmooveW** [comment]
The one at developer.android.com/kotlinplayground is doing the same thing, assuming these are different instances and not just different front ends to the same thing. Suggests there is something wrong with Jetbrains.

**Comment by Diegomaxi3** [comment]
https://play.kotlinlang.org/          -> change setting to JS, it will execute your program. I don't Know if it's the best way, but it give me time to practice.

**Comment by nikpachoo** [comment]
Thank you all for participating; everything works now.
We understand that such downtime is highly undesirable, and we will make our efforts to exclude such situations in the future.
