### ISSUE TITLE
Copy sharable link to clipboard: the button sometimes doesn't work

### ISSUE THREAD

**Issue by Deleplace** [JetBrains/kotlin-playground#144]
Thank you for the very nice Playground and the very useful sharable shortened links.

![image](https://user-images.githubusercontent.com/13508141/149505829-956f6e08-fb16-41ba-8fcc-e132678d907a.png)

### Expected behaviour (usually observed)

- I click Share in the right column
- I click the "Copy link to clipboard" button
  - The text "Copied" shows up
  - The link has been copied to the clipboard
 
### Abnormal behaviour (often observed)

- I click Share in the right column
- I click the "Copy link to clipboard" button
  - Nothing happens
  - Nothing has been copied to the clipboard

Observed in Chrome 97.0.4692.71 (64-bit) Linux.

**Comment by Deleplace** [comment]
In the "abnormal behaviour" scenario, the link has been correctly generated and is already displayed in the popin. I'm confident this is a frontend problem browser-side, not server-side.

**Comment by nikpachoo** [comment]
Hello, @Deleplace! Yeah, it looks like a problem on the frontend side.
This week we will release a significant update in which this problem should be fixed. We'll double-check it for sure.
Thank you a lot for reporting the issue.

**Comment by nikpachoo** [comment]
Fixed 🎉
