### ISSUE TITLE
Kotlin coroutines possible bug with `GlobalScope.launch`

### ISSUE THREAD

**Issue by roksui** [JetBrains/kotlin-playground#157]
When executing the following code snippet on [Kotlin Playground](https://play.kotlinlang.org/) or [Android Kotlin Playground](https://developer.android.com/training/kotlinplayground), an unexpected behavior occurs.

```kotlin
fun main() {
    GlobalScope.launch {
        delay(1000L)
        println("World!")
    }
    println("Hello!")
    runBlocking {
        delay(700L) // Testing by modifying this delay time
    }
}
```

Since the delay time in the `runBlocking` block is 700ms, the expected output would be:
```
Hello!
```

However, the actual output is:
```
World! Hello!
```

It works find when run on IntelliJ IDEA, hence I assume it might be a bug related to the Playground when combined with coroutines.

**Comment by phiSgr** [comment]
Unmerged fix here: https://github.com/JetBrains/kotlin-compiler-server/pull/618

**Comment by roksui** [comment]
@phiSgr Confimed that it is working as expected now. Thank you!
