### ISSUE TITLE
Error when creating own instance using NPM

### ISSUE THREAD

**Issue by msasikanth** [JetBrains/kotlin-playground#19]
I have tried creating my own instance using NPM, but once I added `var playground = require('kotlin-playground');` to my js file I am getting ReferenceError: "navigator is not defined".

**Comment by AlexanderPrendota** [comment]
@msasikanth Hello! If you can provide me a simple stand-alone script, I can take a look.

**Comment by msasikanth** [comment]
I am getting this error as soon as I use the import statement. Even before I write any script. But if still want the code I used it's the same as the one in read me file

import playground from 'kotlin-playground'; document.addEventListener('DOMContentLoaded', () => { playground('code'); // attach to all  elements });

**Comment by AlexanderPrendota** [comment]
@msasikanth I just created simple ReacJS application and install playground via `yarn add playground`.Kotlin-playground works fine for me. So, Did you try to drop all node_modules and install ones again?

**Comment by msasikanth** [comment]
@AlexanderPrendota I created a simple webapp using expressjs from Idea, I added kotlin playground dependency using `npm install kotlin-playground -S`.

But as soon as I use import statement and run the webserver I am getting error again. I tried it without express js and a simple webapp from VisualStudio as well.

**Comment by AlexanderPrendota** [comment]
@msasikanth Oh. I see. Kotlin-Playground runs in the browser, it is written to rely on certain browser APIs. One such API it relies on is [navigator](https://developer.mozilla.org/en-US/docs/Web/API/Navigator). The same behavior as in [CodeMirror](https://codemirror.net/).

Also, you can add playground via script tag:
`<script src="https://unpkg.com/kotlin-playground@1" data-selector="code"></script>`

**Comment by msasikanth** [comment]
So best option right now is to use the ReactJS or use the script tag?

**Comment by AlexanderPrendota** [comment]
@msasikanth Only client side. Kotlin-Playground can only be loaded in a browser environment (because it doesn't do anything useful outside of that).
