### ISSUE TITLE
Kotlin 2.0.0-Beta 2 on Kotlin Playground

### ISSUE THREAD

**Issue by eecs441staff** [JetBrains/kotlin-playground#199]
I was so excited to try the backing field feature of Kotlin 2.0 on Kotlin Playground, only to be met with, "The feature "explicit backing fields" is experimental and should be enabled explicitly."

How do I enable this experimental feature?

**Comment by nikpachoo** [comment]
Hi, @eecs441staff!
Could you please share the code sample you tried to run? There is a button "Copy Link" in Playground for sharing the code.

**Comment by nikpachoo** [comment]
Related PR for Compiler-Server [#197](https://github.com/JetBrains/kotlin-compiler-server/pull/711)

**Comment by eecs441staff** [comment]
Thanks for looking into it. Here's the code.  The commented out version works.

https://pl.kotl.in/eUTQezzuk

**Comment by nikpachoo** [comment]
@eecs441staff, you can try now - https://pl.kotl.in/eUTQezzuk.
Thank you for raising the question!
