### ISSUE TITLE
Erro de código

### ISSUE THREAD

**Issue by Elvistec** [JetBrains/kotlin-playground#214]
Boa tarde a todos!

Sou novo na área e assim como muitos estou tentando aprender programação.
Estou asistindo vídeo aulas. Onde me deparerei com uma atividade.
segue abaixo o código!

fun main() {
    var opcao = 0    
    while (opcao != 2) {        
        println("Escolha uma opção: (1) Iniciar Jogo | (2) Sair ")
        opcao =  readLine()!!.toInt()
        
        if (opcao == 1) {
            println("Iniciando o jogo.... ")            
        }
    }
 }

E paresenta o seguinte erro!

Escolha uma opção: (1) Iniciar Jogo | (2) Sair 
Exception in thread "main" java.lang.NullPointerException
 at FileKt.main (File.kt:5) 
 at FileKt.main (File.kt:-1) 
 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (:-2) 

agradeço se alguém poder me ajudar!

**Comment by JuniorBecari10** [comment]
Boa tarde amigo, aqui não é o lugar ideal para resolver esse tipo de questão, pois aqui é um lugar para reportar problemas com o playground em si, mas eu vou te ajudar: apenas troque `readLine()!!` por `readln()`, ficando dessa forma:

```kt
fun main() {
    var opcao = 0
    
    while (opcao != 2) {
        println("Escolha uma opção: (1) Iniciar Jogo | (2) Sair ")
        opcao = readln().toInt()

        if (opcao == 1) {
            println("Iniciando o jogo.... ")            
        }
    }
}
```

Mas de qualquer forma não vai rodar no playground, pois ele não aceita entrada da stdin (talvez tenha um lugar para especificar isso, mas eu não achei), então recomendo que use uma IDE para executar o seu código, Abraço e fique com Deus!
