### ISSUE TITLE
Enable resizing

### ISSUE THREAD

**Issue by lahanegs** [JetBrains/kotlin-playground#24]
Currently it is unable to resize the working area and output window. It will be great if I will be able to wish to play with code in full screen mode.

**Comment by AlexanderPrendota** [comment]
You can set the height you want like in https://play.kotlinlang.org

**Comment by lahanegs** [comment]
> You can set the height you

I can't find it!

**Comment by AlexanderPrendota** [comment]
```css
.CodeMirror { height:  500px} 
```
