### ISSUE TITLE
Expose launch function

### ISSUE THREAD

**Issue by gzoritchak** [JetBrains/kotlin-playground#26]
We would like to run automatically the code when the user scroll on some examples of code. 

We're currently using some hacking code to do that. It would be better if a launch function would be exposed.

**Comment by AlexanderPrendota** [comment]
I don't think it's a kotlin playground component issue. It's just a plain component to embed in websites for running code. It should not have to adapt to each client.
However you could add the new [`event`](https://github.com/JetBrains/kotlin-playground#events) function you want.

**Comment by gzoritchak** [comment]
> However you could add the new event function you want.
I don't understand what you mean. 

It's not about adapting to each client. Launching the execution from the API seems to be a pretty generic feature. Each client may have its own UI and want to decide at what moment execute the code. We want to produce this [kind of tutorials](http://paperjs.org/tutorials/paths/working-with-path-items/) but without launching all the code by default. We launch it if the bottom of the editor is visible. 

Our code is working without problem. It's just that we had access to the `view.execute` function to launch the code. And if you change the structure of the editor, it will not work anymore.

**Comment by gzoritchak** [comment]
Thank's a lot, it's working fine. 

I have only one concern about the name of the function. `getInstance` is not easy to understand because you are not calling `getInstance` but instead giving a function that is going to be called to retrieve the executor. Maybe something like `grabExecutor`, `instanciatedExecutorCallback`... ? Executor is more precise than "instance" and also the API should emphasize the idea that, as a client of the API, you give a function to be notified of the instanciated executor.

**Comment by AlexanderPrendota** [comment]
🤔
If you print `instance` parameter like 
```js
function getInstance(instance) {
   console.log(instance)
}
```

You may see the current playground state and that state has the `execute` method to run the code.

ps. I like `grabExecutor ` 🙂

**Comment by AlexanderPrendota** [comment]
also I add a little bit API spec [`60282e`](https://github.com/JetBrains/kotlin-playground/commit/60282efe948c1938741fc61a64821384e7d1d6f2).

What do you think about it?

**Comment by AlexanderPrendota** [comment]
meet [`1.15.0`](https://github.com/JetBrains/kotlin-playground/releases/tag/v1.15.0)
