### ISSUE TITLE
Waiting for try.kotlinlang.org

### ISSUE THREAD

**Issue by gzoritchak** [JetBrains/kotlin-playground#28]
I didn't find the sequence to reproduce it but quite often the browser indicates that it is waiting for the server (even if the result seems to came back).

![image](https://user-images.githubusercontent.com/1110254/47957728-c3b38280-dfbb-11e8-8001-8716173dd48c.png)

**Comment by LouisCAD** [comment]
I'm also encountering frequent "Waiting for try.kotlinlang.org" messages from the browser when on a website with Kotlin playgrounds.

**Comment by AlexanderPrendota** [comment]
🤔🧐
Actually I can not reproduced it. Why are you worried?

**Comment by AlexanderPrendota** [comment]
waiting for compile.data2viz.io? 
Wwe're loading javascript libraries like `kotlin.js` from try.kotl.in into iframe for compilation code on target platform JS. 
Why it's an issue? =)

**Comment by AlexanderPrendota** [comment]
I guess it's depend on internet connection

**Comment by LouisCAD** [comment]
This screenshot has been taken on 300-700Mbps fiber connection, well after
loading of compilation and run result. It never goes away once I see it,
unless I close the tab.

**Comment by gzoritchak** [comment]
It's an issue
 1. because it adds a rectangle on top of the page which is not nice,
 2. it gives a bad feeling to the user that thinks something didn't load,
 3. I don't like to leave something weird without understanding ;-)

No, it's not an internet connection problem. It's very easy to reproduce on https://play.kotlinlang.org/byExample/09_Kotlin_JS/05_Canvas 
Just run it few times.

**Comment by AlexanderPrendota** [comment]
Okay! I'll take a look

<img width="250" alt="screen shot 2018-11-06 at 2 42 41 pm" src="https://user-images.githubusercontent.com/10503748/48062155-3bf39100-e1d2-11e8-9d7f-9cc1b9f78ac9.png">

**Comment by gzoritchak** [comment]
I can now add a new element on the "why this is an issue" list.

We are implementing an local history of the code using HTML5 `history.pushState()`. It's working fine until this "waiting for ..." appears.

**Comment by gzoritchak** [comment]
Also we need the place for our footer. See https://play.data2viz.io/sketch/

![image](https://user-images.githubusercontent.com/1110254/48973856-a6695580-f049-11e8-8ef6-5333c4bd0422.png)

**Comment by AlexanderPrendota** [comment]
I guess it's due to Iframe reasons: https://stackoverflow.com/questions/23851818/chrome-iframe-history-not-behaving-correctly-with-2-or-more-iframes-on-page-ve. Probably..
I'll try to find the reason of the problem.

**Comment by gzoritchak** [comment]
It's the same for firefox, even with one iframe. See on https://play.data2viz.io/sketch/

**Comment by AlexanderPrendota** [comment]
Yep I see. If you force drop the iframe the inscription will disappear

**Comment by gzoritchak** [comment]
What do you mean by " If you force drop the iframe".

**Comment by AlexanderPrendota** [comment]
Just remove the iframe from DOM elements

**Comment by AlexanderPrendota** [comment]
@gzoritchak I guest it's due to Jquery library. Why? I still have no idea. Could you drop default Jquery lib from your side and test?

**Comment by AlexanderPrendota** [comment]
hm, in private mode it works fine

**Comment by gzoritchak** [comment]
It's not a problem of jquery. Without it the problem is still here.

**Comment by AlexanderPrendota** [comment]
Yes I know =) I've already tested it. It's a problem around the iframe

**Comment by gzoritchak** [comment]
During the fetch from the iframe? whatwg-fetch?

**Comment by AlexanderPrendota** [comment]
I updated `whatwg-fetch` to the last version today

**Comment by AlexanderPrendota** [comment]
really? =)

**Comment by gzoritchak** [comment]
After the update, the problem completely disappeared for my colleague @azertypow. I still had it but less frequently. We checked the difference between our configuration and after Adblock uninstall (pause wasn't enough) on my **chrome** the problem also disappeared. 

But on firefox, without any plugin and also in private mode, the problem is still here...

**Comment by AlexanderPrendota** [comment]
I released the version 1.18.0. Let's test.
