### ISSUE TITLE
No completion when using folded code

### ISSUE THREAD

**Issue by gzoritchak** [JetBrains/kotlin-playground#29]
When using folded code (with line/to attributes or //sampleStart //sampleEnd comments), the editor doesn't propose code completion.

On [this example](https://play.data2viz.io/tutorials/getting-started/) completion is working (try to change the color by typing Colors.Web.b + completion).

On the examples of [this page](https://play.data2viz.io/tutorials/colors/), it's not working.

When expanding the code by clicking on the + icon, the completion is working again. 

The request for completion only contains the content of the folded code (not the complete code) and also the line number is false.

**Comment by AlexanderPrendota** [comment]
Yes. I know. It's a very very very old issue. 
We have two different editor when we use the folded mode. It's not easy to get actual character and line position in folded code. 

Probably we can use codemirror [`folded mode`](https://codemirror.net/demo/folding.html) but actually I'm not sure it helps.

**Comment by AlexanderPrendota** [comment]
😄
I guess the code completion it's not main feature in folded code 😉.
So I could not found fast solution on this problem :( Probably I'll take a look later.

**Comment by gzoritchak** [comment]
Well it is actually. We are going to remove the folded code in our examples.

**Comment by AlexanderPrendota** [comment]
Hmm! It's a good idea! Drop all the the folded code, forget about this bug and close the issue 😉

So. You can take a look on codemirror folded mode. May be it's a good solution on your examples.

**Comment by AlexanderPrendota** [comment]
@gzoritchak as usual I added a little path [`6fc579`](https://github.com/JetBrains/kotlin-playground/commit/6fc5790ba4cb14a440edc86c6ef06dc08b52720d). Please check it on your side.

So, `done, check version 1.15.1` later 😄

**Comment by gzoritchak** [comment]
You also made me discover that, if it's impossible to rewrite history in git, it's possible on github to make some comments disappear. ;-)
