### ISSUE TITLE
Allow to set webDemo URL as runtime parameter

### ISSUE THREAD

**Issue by calvellido** [JetBrains/kotlin-playground#33]
Hi!  In the Arrow library we are keeping a couple of forks of both Try Kotlin and Kotlin Playground. While most of the forked code is only interesting for our purposes, these days a feature request has popped up (https://github.com/arrow-kt/arrow-playground/issues/13) that might be interesting for this project too.

A way of overwriting the server URL at runtime might be interesting for other Kotlin library creators that could easily use another backend compiler in their projects while keep using the main Kotlin Playground code.

Let me know if this would be interesting for Kotlin Playground, if not I'll move to the work to our fork.

Props for the amazing work on both projects!

**Comment by calvellido** [comment]
Yes, I know that it can be changed at build time, but the goal is to have the possibility of overwriting it at runtime (exactly like you mentioned) to test code snippets of possible features not yet published (e.g. when writing docs) and things like that.

**Comment by calvellido** [comment]
While it might not be seen as valuable from a just Kotlin code point of view, for people working on Kotlin libraries it can be really helpful, as you can host a Try Kotlin instance with your library included and then directly use this same Kotlin Playground without the need to build it yourself (probably most of the people behind those libraries won't like/know to fiddle with JS code).

**Comment by AlexanderPrendota** [comment]
Okay! Thank you for the issue! I'll take a look 🙂

**Comment by calvellido** [comment]
Eh!  I can start working on it as soon as today and submit a PR if you'd like, as I was to add it to our fork, but if you prefer to have a look yourself :+1:

**Comment by AlexanderPrendota** [comment]
Feel free to submit the PR. I guess it's a good feature and I try to help you! Thanks!

**Comment by AlexanderPrendota** [comment]
@gzoritchak maybe you are also interested in this issue

**Comment by gzoritchak** [comment]
@AlexanderPrendota could you release this new version? Thanks!

**Comment by gzoritchak** [comment]
Thanks @calvellido and @AlexanderPrendota. 
I just deployed it : https://play.data2viz.io/
