### ISSUE TITLE
Load kotlin.js from unpkg.com

### ISSUE THREAD

**Issue by gzoritchak** [JetBrains/kotlin-playground#41]
As kotlin.js versions are available on npm, it could be more interesting to load it from unpkg.com:
 
1. global CDN,
2. better caching of libraries, 
3. less load on compile server.

**Comment by AlexanderPrendota** [comment]
We could load `kotlin.js` from `https://www.jsdelivr.com/package/npm/kotlin` but I can not find the `1.0.7` version.

**Comment by jimaek** [comment]
There is no 1.0.7 published to npm https://www.npmjs.com/package/kotlin
That's where jsdelivr pulls the data from https://cdn.jsdelivr.net/npm/kotlin/

**Comment by gzoritchak** [comment]
It's still possible to deploy the 1.0.7 version, no?

**Comment by gzoritchak** [comment]
https://youtrack.jetbrains.com/issue/KT-28530

**Comment by gzoritchak** [comment]
@AlexanderPrendota you just removed you vote on the youtrack bug. 
You think its resolution it's not necessary/possible?

**Comment by AlexanderPrendota** [comment]
Oh..I accidentally did it. Sorry!  Fixed! 🙂

**Comment by gzoritchak** [comment]
@AlexanderPrendota : 

@bashor has made some work on the issue. Can you confirm it's okay for you? 

https://youtrack.jetbrains.com/issue/KT-28530#focus=streamItem-27-3541232.0-0

**Comment by gzoritchak** [comment]
Thanks @AlexanderPrendota
