### ISSUE TITLE
 Assigning single elements to varargs in named form is forbidden in Kotlin Koans

### ISSUE THREAD

**Issue by ldu2** [JetBrains/kotlin-playground#44]
So here is the question that always returns the error 
`Assigning single elements to varargs in named form is forbidden`
https://play.kotlinlang.org/koans/Collections/Compound%20tasks/Task.kt
You can just copy and paste the answer to the right place and it will still throw the error. I went through the whole tutorial and almost finish it, 98% done. Just want to get this last one straight. Can you guys take a look at it? Thanks.

**Comment by AlexanderPrendota** [comment]
Hello! Thanks! I will take a look

**Comment by AlexanderPrendota** [comment]
cc @svtk

**Comment by kyp44** [comment]
Having this same issue! Any progress on a fix?

**Comment by AlexanderPrendota** [comment]
Yep! I updated the test files. =)
