### ISSUE TITLE
Editor font size

### ISSUE THREAD

**Issue by rooton** [JetBrains/kotlin-playground#45]
Font is too big. Please add font size change ability to setting.

**Comment by AlexanderPrendota** [comment]
On play.kot.in?

**Comment by AlexanderPrendota** [comment]
Oh. 
Maybe? https://github.com/JetBrains/kotlin-playground/issues/24
You can set the font size you like

**Comment by rooton** [comment]
Really, from developer console?

**Comment by gslahane** [comment]
I had submitted the issue but no satisfying reply

**Comment by AlexanderPrendota** [comment]
@zoobestik could you take a look please?

**Comment by zoobestik** [comment]
@rooton I'm waiting your feedback in #47
