### ISSUE TITLE
data-js-libs not ending in .js

### ISSUE THREAD

**Issue by fgutmann** [JetBrains/kotlin-playground#46]
The `getJsLibraries` function filters out every library that doesn't match the regex `https?://.+\.js$`.

We have a case where we have to append a version code after the library. e.g `https://example.com/lib.js?version=1.2`.

Would you be ok with making the regex more broad or removing it all together?
Does anybody know why it was introduced in the first place?

**Comment by AlexanderPrendota** [comment]
Hi! 
>  making the regex more broad 
Sure. Why not? 🙂

**Comment by fgutmann** [comment]
How broad is fine for you? :-) 

`https?://.*` would make it much more flexible.
Honestly though I don't see much value in the regex at all.

In my opinion it just hides a user error. It was necessary to  read the source code to figure out what was going on.

I prefer to see a script loading failure in the developer console, over having one of the configured libs silently filtered out.
