### ISSUE TITLE
target-platform js indefinite loading with js-libs 

### ISSUE THREAD

**Issue by fgutmann** [JetBrains/kotlin-playground#49]
Multiple `target-platform="js"` playgrounds with different `data-js-libs` on one page don't execute properly. Some of them keep loading indefinitely.

In this example, the second one is broken.
http://www.redsource.at/playground/kotlin-playground-js-js-libs.html

**Comment by AlexanderPrendota** [comment]
Hi! Thanks!
Ah I see. I have forgotten about external JS libs. So let me have a look at your solution. Thanks

**Comment by fgutmann** [comment]
Hi Alexander!

You are very welcome. Thanks for providing this nice tool. It makes teaching kotlin way more easy :-)

As stated in the PR, the solution is not perfect yet. In my opinion in the end it will be best to have a separate iframe for each `js` executable too. Basically we would just handle it the same way like `canvas` with `data-output-height="0"`.

**Why I think this is a good idea**

Firstly it allows multiple executables to run side by side and there is no chance of interference. Especially when explaining coroutines, timeouts and so forth, longer running codes can be quite common.

Secondly for me as a user it was quite unclear what the difference between `canvas` and `js` actually is. Both are executed client-side and canvas doesn't provide any canvas specific features (e.g. no canvas is created for you). You can actually run the exact same code written for `canvas` in `js` mode. The only difference between them is that you don't see the DOM output in `js` mode.

Thirdly it simplifies the code. We would only have one way how iframes are handled.

**Way forward**

Please let me know what you think of this approach. Did I forget any important points or misunderstood the difference between `js` and `canvas`?

If you agree, I'm happy to implement the changes. It won't be much work based on the current PR.

Also I would like to implement support for async `println()` statements for `js` and `canvas` in the near future. Currently their output is swallowed. When we have support for this, the shortcomings of the "one iframe for multiple executables" approach will start to be more visible.

**Comment by AlexanderPrendota** [comment]
@fgutmann Hi! If I can not close the console. I got the
```
executable-fragment.js:232 Uncaught TypeError: Cannot read property 'reloadIframeScripts' of undefined
    at ExecutableFragment.onConsoleCloseButtonEnter (executable-fragment.js:232)
    at onclick.callback (EventListener.js:23)
```

after your changes. Could you take a look please?

**Comment by AlexanderPrendota** [comment]
I can not create a new version :(

**Comment by AlexanderPrendota** [comment]
So I added a simple condition. Ok for u? Please

**Comment by fgutmann** [comment]
You're totally right, I forgot to test to close the console for Java.
The condition is the proper fix. Thank you!

**Comment by AlexanderPrendota** [comment]
You are welcome :)
