### ISSUE TITLE
change mentions of npm in readme to yarn

### ISSUE THREAD

**Issue by fgutmann** [JetBrains/kotlin-playground#56]
Using `npm` can cause issues because it may resolve to different dependency versions than `yarn`. We have commited a `yarn.lock` file but no equivalent file for `npm`.

For that reason we should change the mentions of `npm` in `readme.md` to their equivalent `yarn` commands.

If I remember correctly we had already some kind of agreement on this in a dependency-related discussion in one of the pull requests.

**Comment by AlexanderPrendota** [comment]
Thanks =)
