### ISSUE TITLE
How complex could be to compile Java?

### ISSUE THREAD

**Issue by jabrena** [JetBrains/kotlin-playground#97]
Hi,

I was reviewing concept in multiple `Kotlin` projects and I would like to do the same stuff with Java.
How complex could be the configuration/change of this project in order to compile Java examples?

Currently if I try to compile Java in any example:

```java
public class Main {
    public static void main(String[] args) {
        System.out.println("This will be printed");
    }
}
```
https://blog.jetbrains.com/kotlin/2018/04/embedding-kotlin-playground/

I receive the following errors:

```
Expecting member declaration
Expecting member declaration
Expecting member declaration
Expecting member declaration
Expecting member declaration
Expecting member declaration
Expecting member declaration
Expecting member declaration
Expecting member declaration
Expecting member declaration
Function declaration must have a name
```

I would like to learn if it is possible to configure in some way current `kotlin-playground` to compile and run Java code.

Many thanks in advance

Juan Antonio

**Comment by AlexanderPrendota** [comment]
Hey, you need to provide a compiler server for java. [Kotlin server example](https://github.com/AlexanderPrendota/kotlin-compiler-server).
